# -*- coding: utf-8 -*-
"""
Created on Tue Nov 11 08:48:40 2025

@author: Paul
"""

services:
  - type: web
    name: haessa-analytics
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: RENDER
        value: "true"
databases:
  - name: haessa_db
    databaseName: haessa_db
    user: haessa_admin
