# -*- coding: utf-8 -*-
"""
Created on Tue Nov 11 08:48:40 2025

@author: Paul
"""

services:
  - type: web
    name: haessa-analytics
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
